version: '2'

services:
  database:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=fucking_around"
      - "MYSQL_USER=jmac"
      - "MYSQL_PASSWORD=root"
      - "MYSQL_ROOT_PASSWORD=root"
    ports:
      - "3307:3306"
  app:
    build:
      context: ./
      dockerfile: ./.docker/app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www/
    links:
      - database
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
  web:
    build:
      context: ./
      dockerfile: ./.docker/web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 8080:80

volumes:
  dbdata: